### ISSUE TITLE
Peanut Remote for TiVo DVR

### ISSUE THREAD

**Issue by tom76017** [tesLAXApp/tesLAX#27]
I know I'm in the wrong place, but this where the Apple App store linked me to support.

Please change the Peanut Remote so that the "ZOOM" becomes the "Back" key.  I think the code is "36".  This works on my TiVo Edge and TiVo Mini.

**Comment by jake-b** [comment]
Wrong place but same developer.  Not sure why the links are messed up.  It's been a long time since I've done any development on Peanut.  I leave it in the AppStore because its free and it still does work.  If time allows (I've since started a family and have small children now) I'll see if I can dig out the source code and see if it still works on modern iOS development tools.  I also don't really use my TiVos much anymore (though I still have a Premeier 4 and a TiVo mini) Thanks for the interest.
