### ISSUE TITLE
Front stator temp in Celsius shows 215

### ISSUE THREAD

**Issue by KoderGuy** [tesLAXApp/tesLAX#28]
The temperature value for front stator in Celsius always shows 215c.  Occasionally it flashes the correct value for an instant but returns to 215 almost immediately.  I double checked in scan my Tesla and the temperature is actually 34c.  This just started happening.

Signal: tempStator376
Version: 2.0.3

Let me know what I can provide to help troubleshoot this.

Thanks
Richard Chong

**Comment by jake-b** [comment]
This is an example of what happens when Tesla changes the data stream.  tesLAX is meant to be configurable so people can update the signals as they change.  I do not maintain the DBCs or signal decoding rules.  We rely on the community to do that.  I simply provide a super configurable app, and leave it up to the community to chase Tesla as they make changes

that said, there are a couple of profiles I posted in the tesLAX discord that will be part of the next release.  I believe this change is accounted for in those profiles.  If you’re not on discord I can post them the GitHub.

**Comment by jake-b** [comment]
I have uploaded the TLP files into this git repository.  If you are an 'extra strength' user, you should be able to import them into your presets list.  You can also find me on Discord for additional help.

**Comment by jake-b** [comment]
tesLAX 2.1 is rolling out to the AppStore now (slowly) and contains some new presets that should fix some of these signals.  Again, I can't play "cat and mouse" should Tesla decide to change the signals again.  This is why tesLAX "Extra Strength" gives users the ability to edit the signals themselves and keep up with the latest changes discovered by the community.

I will close this ticket for now, if you have any other issues, feel free to reach out.
